<?php
/** DESIGN REMINDER: Collector's Folio — use generous space, field-study imagery, editorial modules, and a real WooCommerce collection when products exist. */
get_header();
$theme_uri = get_stylesheet_directory_uri();
$shop_url  = uniqueperspective8_shop_url();
?>
<main><section class="hero"><div class="hero-copy"><p class="eyebrow"><i></i><?php esc_html_e( 'Ethical mineral atelier · British Columbia', 'uniqueperspective8' ); ?></p><h1><?php esc_html_e( 'Earth,', 'uniqueperspective8' ); ?><br><?php esc_html_e( 'held', 'uniqueperspective8' ); ?> <em><?php esc_html_e( 'differently.', 'uniqueperspective8' ); ?></em></h1><p class="hero-intro"><?php esc_html_e( 'Objects of rare presence—hand-selected from the landscape, then considered for the keeping.', 'uniqueperspective8' ); ?></p><div class="hero-actions"><a class="button button--paper" href="#collection"><?php esc_html_e( 'Follow the origin', 'uniqueperspective8' ); ?> <span>↓</span></a><a class="text-link" href="#atelier"><?php esc_html_e( 'Our point of view', 'uniqueperspective8' ); ?> <span>↗</span></a></div></div><figure class="hero-visual"><div class="hero-image-wrap"><img src="<?php echo esc_url( $theme_uri . '/assets/luxury/hero-mineral.jpg' ); ?>" alt="<?php esc_attr_e( 'Blue-green mineral specimen resting on limestone', 'uniqueperspective8' ); ?>"><div class="image-edition"><span><?php esc_html_e( 'Field study', 'uniqueperspective8' ); ?></span><b>08</b></div></div><figcaption><span><?php esc_html_e( 'Selected slowly.', 'uniqueperspective8' ); ?></span> <?php esc_html_e( 'Made to outlast a season.', 'uniqueperspective8' ); ?></figcaption></figure><span class="hero-number">001</span></section>

<section class="atelier-section" id="atelier"><p class="section-rail">01 / <?php esc_html_e( 'The atelier', 'uniqueperspective8' ); ?></p><div class="atelier-head"><p class="eyebrow eyebrow--ink"><i></i><?php esc_html_e( 'A practice of attention', 'uniqueperspective8' ); ?></p><h2><?php esc_html_e( 'Made by the landscape.', 'uniqueperspective8' ); ?><br><?php esc_html_e( 'Finished with restraint.', 'uniqueperspective8' ); ?></h2></div><div class="atelier-body"><p><?php esc_html_e( 'Unique Perspective 8 brings a slower lens to minerals and handcrafted adornment. We are drawn to the marks time leaves behind—the fracture, the inclusion, the unrepeatable shade of a stone found in its own terrain.', 'uniqueperspective8' ); ?></p><p><?php esc_html_e( 'Every piece begins as a field discovery and is offered with the origin still visible. Nothing is overworked. Nothing is made to hurry.', 'uniqueperspective8' ); ?></p><a class="text-link text-link--ink" href="#origin"><?php esc_html_e( 'Read the field notes', 'uniqueperspective8' ); ?> <span>↗</span></a></div><aside class="atelier-note"><?php esc_html_e( 'Ethical minerals', 'uniqueperspective8' ); ?><br><?php esc_html_e( 'Handcrafted jewelry', 'uniqueperspective8' ); ?><br><?php esc_html_e( 'Conscious living', 'uniqueperspective8' ); ?></aside></section>

<section class="collection-section" id="collection"><div class="collection-intro"><p class="eyebrow eyebrow--ink"><i></i><?php esc_html_e( 'Current collection', 'uniqueperspective8' ); ?></p><h2><?php esc_html_e( 'A collection with a', 'uniqueperspective8' ); ?><br><em><?php esc_html_e( 'past tense.', 'uniqueperspective8' ); ?></em></h2><p><?php esc_html_e( 'Start with the surface. Stay for the story beneath it.', 'uniqueperspective8' ); ?></p></div><div class="collection-grid"><?php
$products = new WP_Query( array( 'post_type' => 'product', 'posts_per_page' => 3, 'post_status' => 'publish' ) );
$fallback = array( array( 'Unearthed', 'Raw mineral forms selected for their natural architecture, color, and sense of place.' ), array( 'Held close', 'Quiet jewelry and objects finished with respect for the material’s original character.' ), array( 'One of one', 'Singular pieces with the markings and small histories that cannot be repeated.' ) );
if ( $products->have_posts() ) : $index = 0; while ( $products->have_posts() ) : $products->the_post(); $index++; ?><article class="object-card object-card--<?php echo esc_attr( $index === 1 ? 'moss' : ( $index === 2 ? 'sand' : 'clay' ) ); ?>"><span>0<?php echo esc_html( $index ); ?></span><div class="contours"></div><div><h3><?php the_title(); ?></h3><p><?php echo esc_html( wp_trim_words( get_the_excerpt(), 18 ) ); ?></p><a href="<?php the_permalink(); ?>"><?php esc_html_e( 'View object', 'uniqueperspective8' ); ?><b>↗</b></a></div></article><?php endwhile; wp_reset_postdata(); else : foreach ( $fallback as $index => $item ) : ?><article class="object-card object-card--<?php echo esc_attr( $index === 0 ? 'moss' : ( $index === 1 ? 'sand' : 'clay' ) ); ?>"><span>0<?php echo esc_html( $index + 1 ); ?></span><div class="contours"></div><div><h3><?php echo esc_html( $item[0] ); ?></h3><p><?php echo esc_html( $item[1] ); ?></p><a href="<?php echo esc_url( $shop_url ); ?>"><?php esc_html_e( 'Discover', 'uniqueperspective8' ); ?><b>↗</b></a></div></article><?php endforeach; endif; ?></div><a class="collection-link" href="<?php echo esc_url( $shop_url ); ?>"><?php esc_html_e( 'View collection', 'uniqueperspective8' ); ?> <span>↗</span></a></section>

<section class="specimen-section"><div class="specimen-image"><img src="<?php echo esc_url( $theme_uri . '/assets/luxury/specimen-study.jpg' ); ?>" alt="<?php esc_attr_e( 'Curated study of raw and polished mineral specimens', 'uniqueperspective8' ); ?>"></div><div class="specimen-panel"><p class="eyebrow"><i></i><?php esc_html_e( 'Object notes', 'uniqueperspective8' ); ?></p><blockquote>“<?php esc_html_e( 'A stone does not need to be perfect to be extraordinary. It only needs to be itself.', 'uniqueperspective8' ); ?>”</blockquote><p class="small-label"><?php esc_html_e( 'A guiding thought at the atelier', 'uniqueperspective8' ); ?></p><div class="specimen-metrics"><p><b>01</b><?php esc_html_e( 'Land', 'uniqueperspective8' ); ?><br><?php esc_html_e( 'first', 'uniqueperspective8' ); ?></p><p><b>02</b><?php esc_html_e( 'Hands', 'uniqueperspective8' ); ?><br><?php esc_html_e( 'second', 'uniqueperspective8' ); ?></p><p><b>03</b><?php esc_html_e( 'Yours', 'uniqueperspective8' ); ?><br><?php esc_html_e( 'always', 'uniqueperspective8' ); ?></p></div></div></section>

<section class="origin-section" id="origin"><figure class="origin-image"><img src="<?php echo esc_url( $theme_uri . '/assets/luxury/field-study.jpg' ); ?>" alt="<?php esc_attr_e( 'Mist over a British Columbia riverbank and stones', 'uniqueperspective8' ); ?>"><figcaption>49° 17' N · 123° 07' W</figcaption></figure><div class="origin-copy"><p class="eyebrow eyebrow--ink"><i></i><?php esc_html_e( 'The origin', 'uniqueperspective8' ); ?></p><h2><?php esc_html_e( 'Close to where', 'uniqueperspective8' ); ?><br><?php esc_html_e( 'the earth speaks.', 'uniqueperspective8' ); ?></h2><p><?php esc_html_e( 'From river-worn edges to the rougher ground beyond them, our point of view remains local, curious, and led by the material itself.', 'uniqueperspective8' ); ?></p><a class="button button--outline" href="#journal"><?php esc_html_e( 'Enter the field journal', 'uniqueperspective8' ); ?> <span>↗</span></a></div></section>

<section class="journal-section" id="journal"><div class="journal-top"><p class="eyebrow eyebrow--ink"><i></i><?php esc_html_e( 'From the journal', 'uniqueperspective8' ); ?></p><h2><?php esc_html_e( 'Notes on collecting', 'uniqueperspective8' ); ?><br><em><?php esc_html_e( 'with intention.', 'uniqueperspective8' ); ?></em></h2></div><article class="journal-entry"><span><?php esc_html_e( 'Entry 08', 'uniqueperspective8' ); ?></span><h3><?php esc_html_e( 'The luxury of knowing where something began.', 'uniqueperspective8' ); ?></h3><a href="#top" aria-label="<?php esc_attr_e( 'Return to the beginning', 'uniqueperspective8' ); ?>">↗</a></article></section></main>
<?php get_footer(); ?>
